defaults: &defaults
  host: localhost
  encoding: unicode

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mmp
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
