defaults: &defaults
  host: localhost
  encoding: utf8

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  template: template0
  database: mmp
  username: <%= ENV['MMP_PG_USER'] %>
  password: <%= ENV['MMP_PG_PASS'] %>
