version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - larouxn
    default_labels:
      - "gem upgrades"

    version_requirement_updates: "auto"
